/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Sport = IDL.Variant({
  'baseball' : IDL.Null,
  'basketball' : IDL.Null,
  'swimming' : IDL.Null,
  'volleyball' : IDL.Null,
  'football' : IDL.Null,
  'yoga' : IDL.Null,
  'cycling' : IDL.Null,
  'tennis' : IDL.Null,
  'skiing' : IDL.Null,
  'badminton' : IDL.Null,
});
export const ActivityLog = IDL.Record({
  'date' : IDL.Text,
  'squats' : IDL.Nat,
  'pushups' : IDL.Nat,
  'steps' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'fitnessGoals' : IDL.Text,
  'name' : IDL.Text,
  'selectedSport' : Sport,
  'activityPublic' : IDL.Bool,
  'followers' : IDL.Vec(IDL.Principal),
  'following' : IDL.Vec(IDL.Principal),
  'friends' : IDL.Vec(IDL.Principal),
  'friendRequests' : IDL.Vec(IDL.Principal),
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, Sport], [], []),
  'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getActivityLogsForCaller' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getActivityLogsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logActivity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Sport = IDL.Variant({
    'baseball' : IDL.Null,
    'basketball' : IDL.Null,
    'swimming' : IDL.Null,
    'volleyball' : IDL.Null,
    'football' : IDL.Null,
    'yoga' : IDL.Null,
    'cycling' : IDL.Null,
    'tennis' : IDL.Null,
    'skiing' : IDL.Null,
    'badminton' : IDL.Null,
  });
  const ActivityLog = IDL.Record({
    'date' : IDL.Text,
    'squats' : IDL.Nat,
    'pushups' : IDL.Nat,
    'steps' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'fitnessGoals' : IDL.Text,
    'name' : IDL.Text,
    'selectedSport' : Sport,
    'activityPublic' : IDL.Bool,
    'followers' : IDL.Vec(IDL.Principal),
    'following' : IDL.Vec(IDL.Principal),
    'friends' : IDL.Vec(IDL.Principal),
    'friendRequests' : IDL.Vec(IDL.Principal),
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, Sport], [], []),
    'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getActivityLogsForCaller' : IDL.Func(
        [],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getActivityLogsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logActivity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };